.\" Process this file with
.\" groff -man -Tascii tavs.8
.\"
.TH TAVS 8 "JUNE 2010" Linux "System Utilities"
.SH NAME
tavs - Tier1 Array Verification Scheduler
.SH DESCRIPTION
.B tavs
is the name for a suite of tools that schedule and track the verification of logical devices on hardware RAID controllers.  See the individual man pages listed in the
.B SEE ALSO
section for more details on their usage.

.SH AUTHOR
James Thorne <james.thorne@stfc.ac.uk>
.SH SEE ALSO
.BR tavs-start-verifies (8),
.BR tavs-schedule-verify (8)
